Abbas-01-html
NextGenDevOrg/01-HTML-Learning pull request #11
Opened 2021-10-20 13:25 UTC by AbbasShaikh0304

html Basic Project

2021-10-21 04:56 UTC, AlishaPrasad commented on tasks-by-users/AbbasShaikh0304/01-Project/Style.css
> +}
Where is this css used in the code? I dont see any Heading or Genre classes added in html files.

2021-10-21 11:27 UTC, AbbasShaikh0304 commented on tasks-by-users/AbbasShaikh0304/01-Project/index.html
> +            <img src="img/Comic.jpg" width="100px" height="100px" /><a href="">Comic</a>
made alt changes @faran4engg

2021-10-21 11:28 UTC, AbbasShaikh0304 commented on tasks-by-users/AbbasShaikh0304/01-Project/index.html
> +    <h2>Genre</h2>
That Css file was add mistakenly, i removed that file @faran4engg

2021-10-30 09:33 UTC, faran4engg requested changes
add .vscode folder in .gitignore

2021-10-30 09:34 UTC, faran4engg requested changes
what is this readmme.md, remove if unnecessary

2021-10-31 09:06 UTC, anask601 approved these changes

2021-10-31 11:13 UTC, faran4engg requested changes
@AbbasShaikh0304 , is this PR intended to be closed ( NO MERGE )

2021-11-13 08:08 UTC, nehalskdev commented
Good one

2021-11-13 12:35 UTC, closed without merging